# Generated by Django 3.2.6 on 2021-09-01 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DjangoClasses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=50)),
                ('courseNumber', models.IntegerField(default='', max_length=10)),
                ('instructorName', models.CharField(default='', max_length=80)),
                ('duration', models.FloatField(default='', max_length=30)),
            ],
        ),
    ]
